[package]
name = "randfile"
version = "0.1.0"
authors = ["Kaiyin Zhong <kindlychung@gmail.com>"]

[dependencies]
rand = "0.3"
docopt = "0.6"
rustc-serialize = "0.3"
docopt_macros = "0.6"

[[bin]]
name = "randfile"


